meta_product_name: "GorillaTrip"
meta_title: "GorillaTrip - Pars en toute tranquillité"
meta_description: "Vaccins, visas, précautions, recommandations... tu ne sais plus où donner de la tête avant même d'être parti ? On peut t'aider !"
meta_image: "cover_gorillatrip.jpg" # should exist in `app/assets/images/`
